apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: my-springboot-app
        image: azurecontainerkrss.azurecr.io/springboot-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: my-springboot-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: springboot-app
