apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-springboot-app-v1-deployment
spec:
  replicas: 2
  selector:
    matchLables:
      app: my-springboot-app
  templet:
    metadata:
      lables:
        app: my-springboot-app
    spec:
      containers:
      - name: my-springboot-app
        image: azurecontainerkrss.azurecr.io/my-springboot-app:latest
        imagepullpolicy: Always
        ports:
        - containerport: 8080
    apiVersion: v1
    kind: Service
    metadata:
      lables:
        app: my-springboot-app
        k8s-app: my-springboot-app
      name: my-springboot-app
      spec:
        ports:
        - name: http
          port: 80
          protocol: TCP
          targetport: 8080
        type: LoadBalancer
        selector:
          app: my-springboot-app
