on:
  push:
    branches: [ "main"]
  pull_request:
    branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        env:
          AZURE_CONTAINER_REGISTRY: "azurecontainerkrss"
          CONTAINER_NAME: "springboot-appe"
          RESOURCE_GROUP: "azure-terraform-rg"
          CLUSTER_NAME: "azureakskrss"

        steps:
        - uses: actions/checkout@v3
        - name: set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Build with maven
          run: mvn clean install
        - name: Login to the azure
          uses: azure/login@v1
          with:
              creds: '${{ secrets.AZURE_CREDENTIALS }}'
        - name: BUILD AND PUSH Docker image
          run: |
              docker build . --file Dockerfile --tag my-springboot-app:latest
              docker login azurecontainerkrss.azurecr.io -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
              docker tag my-springboot-app:latest azurecontainerkrss.azurecr.io/my-springboot-app:latest
              docker push azurecontainerkrss.azurecr.io/my-springboot-app:latest
        - name: Deploy to aks
          run: | 
               az aks get-credentials --resource-group azure-terraform-rg --name azureakskrss
               kubectl config use-context azureakskrss
               kubectl apply -f aks-deploy-from-acr.yaml
            
      
