on:
  push:
    branches: [ "main"]
  pull_request:
    branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
        - name: Build with maven
          run: mvn clean install
        - name: Login to the azure
          uses: azure/login@v1
          with:
              creds: '${{ secrets.AZURE_CREDENTIALS }}'
        - name: BUILD AND PUSH Docker image
          run: |
              docker build --file Dockerfile --tag springboot-app:v1
              docker login azurecontainerkrss.azure.io -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
              docker tag springboot-app:v1 azurecontainerkrss.azure.io/springboot-app:v1
              docker push azurecontainerkrss.azure.io/springboot-app:v1
        - name: Deploy to aks
          run: | 
               az aks get-credentials --resource-group azure-terraform-rg --azureakskrss
               kubectl config use-context azureakskrss
               kubectl apply -f aks-deploy.yaml
            
      
